/* ============================================================================
   INSERT COIN — preguntas.js  (banco de la Trivia de Cine)
   ----------------------------------------------------------------------------
   Cada pregunta tiene:
     cat   → categoría: "hollywood" | "argentino" | "animacion" | "mixto"
     dif   → dificultad: 1 (fácil) · 2 (media) · 3 (difícil)
     q     → la pregunta
     ops   → las 4 opciones
     ok    → índice (0–3) de la opción correcta
     pista → texto que revela el comodín "Pista"
     dato  → curiosidad que se muestra después de responder

   ★ PARA SUMAR PREGUNTAS: copiá un bloque, cambialo y listo. Verificá que "ok"
   apunte a la opción correcta (se cuenta desde 0). Mantené 4 opciones.
   ============================================================================ */

window.TRIVIA_PREGUNTAS = [

  /* ===================== HOLLYWOOD Y SAGAS ===================== */
  { cat:"hollywood", dif:1,
    q:"¿Quién dirigió la trilogía original de 'El Señor de los Anillos'?",
    ops:["Guillermo del Toro","Peter Jackson","Christopher Nolan","James Cameron"], ok:1,
    pista:"Es neozelandés y filmó todo en su país.",
    dato:"Se rodó íntegramente en Nueva Zelanda durante más de un año seguido." },

  { cat:"hollywood", dif:2,
    q:"¿En qué año se estrenó la primera 'Star Wars' (Una nueva esperanza)?",
    ops:["1975","1977","1980","1983"], ok:1,
    pista:"Fue en la segunda mitad de los 70.",
    dato:"Al estrenarse se llamaba solo 'Star Wars'; el 'Episodio IV' se agregó después." },

  { cat:"hollywood", dif:1,
    q:"¿Qué actor interpreta a Iron Man / Tony Stark en el Universo Marvel?",
    ops:["Chris Evans","Robert Downey Jr.","Mark Ruffalo","Chris Hemsworth"], ok:1,
    pista:"Debutó en el papel en 2008.",
    dato:"Su sueldo por película llegó a ser de los más altos de Hollywood." },

  { cat:"hollywood", dif:1,
    q:"¿Quién dirigió 'Titanic' (1997)?",
    ops:["Steven Spielberg","James Cameron","Ridley Scott","Ron Howard"], ok:1,
    pista:"También dirigió 'Avatar'.",
    dato:"Ganó 11 Oscars, récord que comparte con 'Ben-Hur' y 'El retorno del rey'." },

  { cat:"hollywood", dif:2,
    q:"En 'El Padrino', ¿qué actor interpreta a Michael Corleone?",
    ops:["Al Pacino","Robert De Niro","Marlon Brando","Robert Duvall"], ok:0,
    pista:"Años después haría de Tony en 'Scarface'.",
    dato:"Marlon Brando interpreta a Vito, su padre." },

  { cat:"hollywood", dif:2,
    q:"¿Cuál es el nombre del personaje de Anthony Hopkins en 'El silencio de los inocentes'?",
    ops:["Norman Bates","Hannibal Lecter","John Doe","Patrick Bateman"], ok:1,
    pista:"Es un psiquiatra caníbal.",
    dato:"Hopkins ganó el Oscar apareciendo en pantalla apenas unos 16 minutos." },

  { cat:"hollywood", dif:1,
    q:"En la saga 'Harry Potter', ¿cómo se llama el colegio de magia?",
    ops:["Durmstrang","Hogwarts","Beauxbatons","Ilvermorny"], ok:1,
    pista:"Su director es Albus Dumbledore.",
    dato:"Las otras tres también son escuelas de magia dentro de ese universo." },

  { cat:"hollywood", dif:2,
    q:"¿Qué actor interpretó al Joker en 'Batman: El caballero de la noche' (2008)?",
    ops:["Joaquin Phoenix","Jack Nicholson","Heath Ledger","Jared Leto"], ok:2,
    pista:"Ganó un Oscar póstumo por ese papel.",
    dato:"Joaquin Phoenix también ganó un Oscar por el Joker, en 2019." },

  { cat:"hollywood", dif:2,
    q:"¿Quién dirigió 'Pulp Fiction' (1994)?",
    ops:["Martin Scorsese","Quentin Tarantino","David Fincher","Los hermanos Coen"], ok:1,
    pista:"Le encantan los diálogos largos y la violencia estilizada.",
    dato:"Ganó la Palma de Oro en Cannes y el Oscar al mejor guion." },

  { cat:"hollywood", dif:1,
    q:"En 'Matrix' (1999), ¿de qué color es la píldora que elige Neo para ver la verdad?",
    ops:["Azul","Roja","Verde","Blanca"], ok:1,
    pista:"La otra opción te devuelve a la ignorancia.",
    dato:"La dirigieron las hermanas Wachowski." },

  { cat:"hollywood", dif:2,
    q:"¿Qué película de Marvel (2019) llegó a ser la más taquillera de la historia?",
    ops:["Avengers: Infinity War","Avengers: Endgame","Black Panther","Spider-Man: No Way Home"], ok:1,
    pista:"Es el cierre de la 'Saga del Infinito'.",
    dato:"Destronó a 'Avatar', que luego recuperó el puesto con una reestrena." },

  { cat:"hollywood", dif:3,
    q:"¿Quién compuso la música de 'Star Wars', 'Tiburón' e 'Indiana Jones'?",
    ops:["Hans Zimmer","John Williams","Ennio Morricone","Danny Elfman"], ok:1,
    pista:"Es la persona viva con más nominaciones al Oscar.",
    dato:"Acumula más de 50 nominaciones al Oscar a lo largo de su carrera." },

  { cat:"hollywood", dif:2,
    q:"En 'Volver al futuro', ¿qué auto funciona como máquina del tiempo?",
    ops:["Ford Mustang","DeLorean DMC-12","Chevrolet Camaro","Cadillac Eldorado"], ok:1,
    pista:"Tiene puertas que se abren hacia arriba.",
    dato:"Necesita alcanzar las 88 millas por hora para viajar en el tiempo." },

  { cat:"hollywood", dif:2,
    q:"¿Quién dirigió 'El origen' (Inception, 2010)?",
    ops:["Denis Villeneuve","Christopher Nolan","Ridley Scott","Alfonso Cuarón"], ok:1,
    pista:"También hizo la trilogía de Batman con Christian Bale.",
    dato:"El famoso trompo del final dejó su destino a interpretación del público." },

  /* ===================== CINE ARGENTINO Y LATINO ===================== */
  { cat:"argentino", dif:2,
    q:"¿Qué película argentina ganó el Oscar a Mejor Película Extranjera en 2010?",
    ops:["Relatos salvajes","El secreto de sus ojos","Nueve reinas","El hijo de la novia"], ok:1,
    pista:"La dirigió Juan José Campanella.",
    dato:"Su escena del estadio de fútbol es un plano secuencia digital memorable." },

  { cat:"argentino", dif:2,
    q:"¿Quién dirigió 'Relatos salvajes' (2014)?",
    ops:["Juan José Campanella","Damián Szifron","Pablo Trapero","Lucrecia Martel"], ok:1,
    pista:"Son seis historias independientes sobre la furia.",
    dato:"Estuvo nominada al Oscar a Mejor Película Extranjera." },

  { cat:"argentino", dif:3,
    q:"En 'Nueve reinas' (2000), ¿qué dúo de estafadores la protagoniza?",
    ops:["Ricardo Darín y Gastón Pauls","Francella y Darín","Sbaraglia y Darín","Peretti y Pauls"], ok:0,
    pista:"Uno es un estafador veterano; el otro, casi un novato.",
    dato:"La dirigió Fabián Bielinsky y tuvo una remake de Hollywood ('Criminal')." },

  { cat:"argentino", dif:3,
    q:"¿Qué película argentina ganó el Oscar extranjero en 1986, la primera de Latinoamérica?",
    ops:["La historia oficial","Camila","La tregua","El secreto de sus ojos"], ok:0,
    pista:"Trata sobre la apropiación de bebés durante la dictadura.",
    dato:"La dirigió Luis Puenzo y marcó un hito para el cine latinoamericano." },

  { cat:"argentino", dif:1,
    q:"¿Qué actor protagoniza 'El secreto de sus ojos' y 'Argentina, 1985'?",
    ops:["Guillermo Francella","Ricardo Darín","Leonardo Sbaraglia","Diego Peretti"], ok:1,
    pista:"Es quizá el actor argentino más internacional.",
    dato:"También protagonizó 'Nueve reinas' y 'El hijo de la novia'." },

  { cat:"argentino", dif:2,
    q:"¿Qué actor, más conocido por la comedia, brilla en un rol dramático en 'El secreto de sus ojos'?",
    ops:["Guillermo Francella","Diego Capusotto","Adrián Suar","Pablo Rago"], ok:0,
    pista:"Hizo de Sandoval, el compañero alcohólico del protagonista.",
    dato:"Su papel sorprendió al gran público por el giro dramático." },

  { cat:"argentino", dif:2,
    q:"La película mexicana 'Roma' (2018), que ganó 3 Oscars, fue dirigida por...",
    ops:["Guillermo del Toro","Alejandro G. Iñárritu","Alfonso Cuarón","Carlos Reygadas"], ok:2,
    pista:"También dirigió 'Gravedad' y 'Y tu mamá también'.",
    dato:"Ganó Mejor Director, Mejor Película Extranjera y Mejor Fotografía." },

  { cat:"argentino", dif:2,
    q:"¿Qué director mexicano ganó el Oscar por 'La forma del agua' (2017)?",
    ops:["Alfonso Cuarón","Guillermo del Toro","Alejandro G. Iñárritu","Emmanuel Lubezki"], ok:1,
    pista:"Le encantan los monstruos y los cuentos oscuros.",
    dato:"Ganó Mejor Director y Mejor Película con un romance entre mujer y criatura." },

  { cat:"argentino", dif:3,
    q:"¿Quién dirigió 'Argentina, 1985' (2022), sobre el Juicio a las Juntas?",
    ops:["Santiago Mitre","Damián Szifron","Juan José Campanella","Benjamín Naishtat"], ok:0,
    pista:"Trabajó antes con Darín en 'La cordillera'.",
    dato:"Ganó el Globo de Oro y estuvo nominada al Oscar extranjero." },

  { cat:"argentino", dif:3,
    q:"¿Qué película brasileña sobre las favelas de Río dirigió Fernando Meirelles (2002)?",
    ops:["Tropa de Élite","Ciudad de Dios","Estación Central","El abrazo de la serpiente"], ok:1,
    pista:"Su título original es 'Cidade de Deus'.",
    dato:"Tuvo 4 nominaciones al Oscar, algo rarísimo para una película brasileña." },

  /* ===================== ANIMACIÓN ===================== */
  { cat:"animacion", dif:1,
    q:"¿Cuál fue la primera película de Pixar, estrenada en 1995?",
    ops:["Bichos","Toy Story","Monsters Inc.","Buscando a Nemo"], ok:1,
    pista:"Sus protagonistas son juguetes.",
    dato:"Fue el primer largometraje hecho enteramente por computadora." },

  { cat:"animacion", dif:2,
    q:"¿Qué estudio japonés produjo 'El viaje de Chihiro' y 'Mi vecino Totoro'?",
    ops:["Studio Ghibli","Toei Animation","Madhouse","Pixar"], ok:0,
    pista:"Lo fundó Hayao Miyazaki.",
    dato:"Su logo es justamente el personaje Totoro." },

  { cat:"animacion", dif:2,
    q:"¿Qué película de Pixar (2017) transcurre en el Día de los Muertos en México?",
    ops:["Coco","El libro de la vida","Encanto","Vivo"], ok:0,
    pista:"Su protagonista, Miguel, sueña con ser músico.",
    dato:"Ganó el Oscar a Mejor Película Animada." },

  { cat:"animacion", dif:2,
    q:"¿Quién dirigió 'El viaje de Chihiro' (2001), ganadora del Oscar?",
    ops:["Hayao Miyazaki","Makoto Shinkai","Isao Takahata","Mamoru Hosoda"], ok:0,
    pista:"Es el maestro más célebre del Studio Ghibli.",
    dato:"Fue la primera (y por años la única) anime en ganar el Oscar animado." },

  { cat:"animacion", dif:1,
    q:"En 'El Rey León' (1994), ¿cómo se llama el padre de Simba?",
    ops:["Scar","Mufasa","Rafiki","Zazu"], ok:1,
    pista:"Su hermano lo traiciona.",
    dato:"La famosa escena de la estampida tardó años en poder animarse." },

  { cat:"animacion", dif:1,
    q:"¿Qué película de Disney (2013) popularizó la canción 'Libre soy'?",
    ops:["Enredados","Frozen","Moana","Encanto"], ok:1,
    pista:"Sus protagonistas son las hermanas Elsa y Anna.",
    dato:"Fue, en su momento, la película animada más taquillera de la historia." },

  { cat:"animacion", dif:1,
    q:"¿Qué película de Pixar ocurre dentro de la cabeza de una niña, entre sus emociones?",
    ops:["Intensa-Mente","Soul","Up","Coco"], ok:0,
    pista:"Alegría, Tristeza y Furia son personajes.",
    dato:"Su título original es 'Inside Out'." },

  { cat:"animacion", dif:2,
    q:"¿De qué estudio es 'Shrek' (2001)?",
    ops:["Pixar","DreamWorks","Disney","Illumination"], ok:1,
    pista:"El mismo estudio de 'Madagascar' y 'Kung Fu Panda'.",
    dato:"Ganó el primer Oscar a Mejor Película Animada de la historia." },

  { cat:"animacion", dif:2,
    q:"En 'Buscando a Nemo', ¿qué tipo de pez es Nemo?",
    ops:["Pez ángel","Pez payaso","Pez cirujano","Pez globo"], ok:1,
    pista:"Es naranja con rayas blancas.",
    dato:"Dory, en cambio, es un pez cirujano azul." },

  { cat:"animacion", dif:2,
    q:"¿Qué película de Pixar abre con la vida muda de una pareja, Carl y Ellie?",
    ops:["Wall-E","Up","Coco","Soul"], ok:1,
    pista:"Después, una casa vuela con miles de globos.",
    dato:"Esos primeros minutos son citados como de los más emotivos del cine animado." },

  { cat:"animacion", dif:2,
    q:"¿Quién pone la voz original (en inglés) de Woody en 'Toy Story'?",
    ops:["Tim Allen","Tom Hanks","Billy Crystal","Robin Williams"], ok:1,
    pista:"También protagonizó 'Forrest Gump'.",
    dato:"Tim Allen, en cambio, es la voz de Buzz Lightyear." },

  { cat:"animacion", dif:1,
    q:"¿Qué película de Disney (2021) está ambientada en Colombia con canciones de Lin-Manuel Miranda?",
    ops:["Coco","Encanto","Vivo","Moana"], ok:1,
    pista:"La familia Madrigal vive en una casa mágica.",
    dato:"La canción 'No se habla de Bruno' fue número uno en muchos países." },

  { cat:"animacion", dif:1,
    q:"¿Cuál es el robot protagonista de la película de Pixar (2008) sobre una Tierra abandonada?",
    ops:["WALL-E","Baymax","Bender","R2-D2"], ok:0,
    pista:"Su trabajo es compactar basura.",
    dato:"Casi no tiene diálogos durante la primera mitad de la película." },

  /* ===================== MIX DE CINE ===================== */
  { cat:"mixto", dif:2,
    q:"¿Qué película ganó el Oscar a Mejor Película en 2020, la primera de habla no inglesa?",
    ops:["1917","Parasite","Joker","Once Upon a Time in Hollywood"], ok:1,
    pista:"Es surcoreana y la dirigió Bong Joon-ho.",
    dato:"También ganó Mejor Director, Guion y Película Internacional la misma noche." },

  { cat:"mixto", dif:2,
    q:"¿De qué película es la frase 'Le haré una oferta que no podrá rechazar'?",
    ops:["Buenos muchachos","El Padrino","Scarface","Casino"], ok:1,
    pista:"La dice Vito Corleone.",
    dato:"Es una de las frases más citadas en la historia del cine." },

  { cat:"mixto", dif:1,
    q:"¿Qué director hizo 'Tiburón', 'E.T.' y 'Jurassic Park'?",
    ops:["George Lucas","Steven Spielberg","Robert Zemeckis","Ridley Scott"], ok:1,
    pista:"Cofundó el estudio DreamWorks.",
    dato:"'Tiburón' es considerada la primera película 'blockbuster' de verano." },

  { cat:"mixto", dif:1,
    q:"La película 'Joker' (2019) está protagonizada por...",
    ops:["Joaquin Phoenix","Heath Ledger","Jared Leto","Jack Nicholson"], ok:0,
    pista:"Bajó muchos kilos para el papel.",
    dato:"Ganó el Oscar a Mejor Actor por esta interpretación." },

  { cat:"mixto", dif:2,
    q:"¿Qué actor protagoniza 'Náufrago', hablando con una pelota llamada Wilson?",
    ops:["Tom Hanks","Brad Pitt","Matt Damon","Tom Cruise"], ok:0,
    pista:"Es el mismo de 'Forrest Gump' y 'Toy Story'.",
    dato:"Wilson, la pelota, se volvió un personaje querido pese a no hablar." },

  { cat:"mixto", dif:3,
    q:"¿Con qué película Leonardo DiCaprio ganó finalmente su primer Oscar (2016)?",
    ops:["El lobo de Wall Street","El renacido","Django sin cadenas","El origen"], ok:1,
    pista:"Sufrió frío extremo filmando en la nieve.",
    dato:"La dirigió Alejandro González Iñárritu, que ganó Mejor Director." },

  { cat:"mixto", dif:1,
    q:"¿Qué saga protagoniza el personaje 'Dominic Toretto'?",
    ops:["Misión Imposible","Rápidos y Furiosos","John Wick","Transformers"], ok:1,
    pista:"Todo es sobre autos, velocidad y 'la familia'.",
    dato:"Lo interpreta Vin Diesel desde la primera película de 2001." },

  { cat:"mixto", dif:3,
    q:"¿Qué película de terror de 1980 dirigió Stanley Kubrick, basada en Stephen King?",
    ops:["It","El resplandor","La cosa","Pesadilla en lo profundo"], ok:1,
    pista:"'¿Estás aquí, Danny?' y un hotel embrujado.",
    dato:"El propio Stephen King no quedó conforme con esta adaptación." },

  { cat:"mixto", dif:3,
    q:"¿Qué película de 1994 transcurre en la prisión de Shawshank?",
    ops:["Pena de muerte","Cadena perpetua (Sueños de libertad)","La milla verde","Escape de Alcatraz"], ok:1,
    pista:"Basada en un relato de Stephen King, sobre la esperanza.",
    dato:"Fracasó en cines pero hoy figura entre las mejores películas de la historia." },

  /* ===================== TERROR Y SLASHER ===================== */
  { cat:"terror", dif:2,
    q:"¿Cómo se llama el asesino enmascarado de la saga 'Halloween'?",
    ops:["Jason Voorhees","Michael Myers","Freddy Krueger","Ghostface"], ok:1,
    pista:"Aterroriza el pueblo de Haddonfield cada 31 de octubre.",
    dato:"Su máscara es, en realidad, una careta del capitán Kirk pintada de blanco." },

  { cat:"terror", dif:1,
    q:"¿Qué asesino usa un guante con cuchillas y ataca dentro de los sueños?",
    ops:["Jason Voorhees","Freddy Krueger","Leatherface","Michael Myers"], ok:1,
    pista:"Su lema: 'si te dormís, morís'.",
    dato:"Lo creó Wes Craven en 1984; un Johnny Depp jovencísimo debutó en esa película." },

  { cat:"terror", dif:2,
    q:"En la saga 'Viernes 13', ¿quién es el asesino de la máscara de hockey?",
    ops:["Jason Voorhees","Norman Bates","Michael Myers","Ghostface"], ok:0,
    pista:"Acecha en el campamento Crystal Lake.",
    dato:"Dato fino: en la primera película (1980) el asesino NO es él, sino su madre." },

  { cat:"terror", dif:2,
    q:"¿Qué slasher de 1996 de Wes Craven revivió el género con el asesino 'Ghostface'?",
    ops:["Scream (Grita antes de morir)","Sé lo que hicieron el verano pasado","Leyenda urbana","Halloween H20"], ok:0,
    pista:"Sus personajes conocen y comentan 'las reglas' del cine de terror.",
    dato:"La máscara de Ghostface se inspira en el cuadro 'El grito' de Munch." },

  { cat:"terror", dif:3,
    q:"¿Qué clásico de 1974 presentó por primera vez a 'Leatherface' y su motosierra?",
    ops:["La masacre de Texas","Las colinas tienen ojos","El pueblo de los malditos","La matanza caníbal"], ok:0,
    pista:"Su título original es 'The Texas Chain Saw Massacre'.",
    dato:"Dirigida por Tobe Hooper, casi no muestra sangre pese a su fama brutal." },

  { cat:"terror", dif:2,
    q:"En 'Psicosis' (1960) de Hitchcock, ¿cómo se llama el dueño del motel?",
    ops:["Norman Bates","Jack Torrance","Patrick Bateman","Hannibal Lecter"], ok:0,
    pista:"Tiene una relación muy extraña con su madre.",
    dato:"La escena de la ducha se montó con unos 78 planos en apenas 45 segundos." },

  { cat:"terror", dif:2,
    q:"¿Qué película de 1973 sobre una niña poseída conmocionó al mundo?",
    ops:["La profecía","El exorcista","El bebé de Rosemary","Poltergeist"], ok:1,
    pista:"Aparecen dos sacerdotes intentando un ritual.",
    dato:"Fue la primera película de terror nominada al Oscar a Mejor Película." },

  { cat:"terror", dif:2,
    q:"¿Quién dirigió 'Huye!' (Get Out, 2017) y '¡Nop!' (Nope)?",
    ops:["Ari Aster","Jordan Peele","Robert Eggers","James Wan"], ok:1,
    pista:"Antes era conocido por la comedia.",
    dato:"Ganó el Oscar al Mejor Guion Original por 'Get Out'." },

  { cat:"terror", dif:3,
    q:"¿Qué director levantó las sagas 'El conjuro', 'Insidious' y la primera 'Saw'?",
    ops:["Eli Roth","James Wan","Rob Zombie","Sam Raimi"], ok:1,
    pista:"Es australiano y también dirigió 'Aquaman'.",
    dato:"Convirtió el terror moderno en un negocio de universos conectados." },

  { cat:"terror", dif:2,
    q:"¿Qué película de 1999 popularizó el 'found footage' con tres jóvenes perdidos en un bosque?",
    ops:["Actividad Paranormal","El proyecto Blair Witch","REC","Cloverfield"], ok:1,
    pista:"'Found footage' = simula ser material real encontrado.",
    dato:"Su marketing hizo creer a mucha gente que las desapariciones eran reales." },

  { cat:"terror", dif:2,
    q:"¿Qué saga gira en torno al asesino 'Jigsaw' y sus trampas mortales?",
    ops:["Hostal","Saw (El juego del miedo)","Cube","Destino final"], ok:1,
    pista:"'¿Querés jugar un juego?'",
    dato:"La primera se rodó en menos de tres semanas y con muy poco presupuesto." },

  { cat:"terror", dif:3,
    q:"¿Qué película de 'terror elevado' (2018) dirigió Ari Aster sobre una familia en duelo?",
    ops:["El legado del diablo (Hereditary)","Babadook","La bruja","It Follows"], ok:0,
    pista:"Una maqueta, una decapitación y un final infernal.",
    dato:"Aster volvería al año siguiente con 'Midsommar'." },

  { cat:"terror", dif:1,
    q:"¿Qué muñeco diabólico protagoniza la saga 'Chucky' (Child's Play)?",
    ops:["Annabelle","Chucky","Billy","Slappy"], ok:1,
    pista:"Es un muñeco pelirrojo poseído por un asesino.",
    dato:"Annabelle, en cambio, pertenece al universo de 'El conjuro'." },

  { cat:"terror", dif:1,
    q:"¿En qué película aparece el payaso 'Pennywise', de una novela de Stephen King?",
    ops:["It (Eso)","Payasos asesinos","Terrifier","La niebla"], ok:0,
    pista:"Sale de las alcantarillas cada 27 años.",
    dato:"Tim Curry lo hizo famoso en 1990; Bill Skarsgård, en las versiones de 2017/2019." },

  { cat:"terror", dif:3,
    q:"¿Cómo se llama el arquetipo de la última sobreviviente típica del slasher?",
    ops:["'Scream Queen'","'Final Girl'","'Last Stand'","'Survivor'"], ok:1,
    pista:"Es la que enfrenta al asesino al final, casi siempre sola.",
    dato:"Laurie Strode ('Halloween') y Sidney Prescott ('Scream') son ejemplos icónicos." },

  /* ===================== TANDA 2 (+100 preguntas) ===================== */

  /* --- Terror y Slasher --- */
  { cat:"terror", dif:2, q:"¿En qué casos reales se basa la saga 'El conjuro'?",
    ops:["Los de Ed y Lorraine Warren","Los de Mulder y Scully","Los de los Cazafantasmas","Los del detective Constantine"], ok:0,
    pista:"Eran un matrimonio de investigadores paranormales.", dato:"Patrick Wilson y Vera Farmiga los interpretan en la saga." },
  { cat:"terror", dif:2, q:"¿Qué muñeca poseída protagoniza un spin-off de 'El conjuro'?",
    ops:["Annabelle","Chucky","M3GAN","Brahms"], ok:0,
    pista:"Está encerrada tras un vidrio en el museo de los Warren.", dato:"Se inspira en una muñeca Raggedy Ann real." },
  { cat:"terror", dif:3, q:"En 'El bebé de Rosemary' (1968), ¿qué resulta ser el bebé?",
    ops:["Hijo del diablo","Un vampiro","Un robot","Gemelos"], ok:0,
    pista:"Los vecinos pertenecen a una secta.", dato:"La dirigió Roman Polanski." },
  { cat:"terror", dif:3, q:"¿Qué película de 1968 de George A. Romero fundó el cine de zombies moderno?",
    ops:["La noche de los muertos vivientes","28 días después","Zombi","Re-Animator"], ok:0,
    pista:"Es en blanco y negro.", dato:"Se hizo con un presupuesto bajísimo y entró al dominio público." },
  { cat:"terror", dif:2, q:"¿Qué actriz interpreta a Laurie Strode en 'Halloween' desde 1978?",
    ops:["Jamie Lee Curtis","Neve Campbell","Sigourney Weaver","Drew Barrymore"], ok:0,
    pista:"Es hija de la actriz de la ducha de 'Psicosis'.", dato:"Su madre, Janet Leigh, protagonizó 'Psicosis'." },
  { cat:"terror", dif:3, q:"¿Qué clásico mudo de vampiros de 1922 fue un plagio no autorizado de 'Drácula'?",
    ops:["Nosferatu","Metrópolis","El gabinete del Dr. Caligari","El golem"], ok:0,
    pista:"Su vampiro se llama Conde Orlok.", dato:"F.W. Murnau lo dirigió; la justicia ordenó destruir las copias." },
  { cat:"terror", dif:3, q:"¿Qué película de terror corporal de 1986 dirigió David Cronenberg?",
    ops:["La mosca","La cosa","Videodrome","Re-Animator"], ok:0,
    pista:"Un científico se fusiona poco a poco con un insecto.", dato:"Jeff Goldblum la protagoniza." },
  { cat:"terror", dif:3, q:"En 'La cosa' (1982) de John Carpenter, ¿qué es la amenaza?",
    ops:["Un alienígena que imita a sus víctimas","Un yeti","Un demonio","Un virus zombi"], ok:0,
    pista:"Nadie sabe quién sigue siendo humano.", dato:"Sus efectos prácticos siguen siendo elogiados hoy." },
  { cat:"terror", dif:3, q:"¿Qué director hizo 'Halloween' (1978) y 'La cosa' (1982)?",
    ops:["John Carpenter","Wes Craven","George Romero","Sam Raimi"], ok:0,
    pista:"Suele componer él mismo la música de sus películas.", dato:"Su estilo definió el slasher y el terror de los 80." },
  { cat:"terror", dif:3, q:"¿Qué saga de terror sobrenatural sigue a la familia Lambert y un lugar llamado 'La Otra Parte'?",
    ops:["Insidious","Sinister","Oculus","Sobrenatural"], ok:0,
    pista:"La crearon James Wan y Leigh Whannell.", dato:"Mezcla viajes astrales con entes demoníacos." },
  { cat:"terror", dif:2, q:"¿Qué saga 'found footage' arranca con una pareja filmando fantasmas en su casa?",
    ops:["Actividad Paranormal","REC","Cloverfield","El proyecto Blair Witch"], ok:0,
    pista:"Usa cámaras de seguridad por la noche.", dato:"Costó muy poco y recaudó cientos de millones." },
  { cat:"terror", dif:3, q:"¿Qué película española de 2007 llevó el 'found footage' zombi a un edificio en cuarentena?",
    ops:["REC","El orfanato","Verónica","Los sin nombre"], ok:0,
    pista:"Una reportera queda atrapada con su camarógrafo.", dato:"Tuvo una remake de Hollywood, 'Quarantine'." },
  { cat:"terror", dif:2, q:"¿Qué película de Jordan Peele (2019) enfrenta a una familia con sus dobles siniestros?",
    ops:["Nosotros (Us)","Candyman","La invitación","Get Out"], ok:0,
    pista:"Los dobles visten de rojo y llevan tijeras.", dato:"Lupita Nyong'o interpreta un doble papel." },
  { cat:"terror", dif:2, q:"¿Qué muñeca con inteligencia artificial protagoniza la película de terror de 2023?",
    ops:["M3GAN","Annabelle","Chucky","Brahms"], ok:0,
    pista:"Su baile se volvió viral antes del estreno.", dato:"Es prima espiritual de Chucky, pero con IA." },
  { cat:"terror", dif:2, q:"¿Qué película de 1979 mezcla ciencia ficción con un alienígena que acecha una nave?",
    ops:["Alien","La cosa","Depredador","Horizonte final"], ok:0,
    pista:"'En el espacio nadie puede oír tus gritos.'", dato:"La dirigió Ridley Scott." },
  { cat:"terror", dif:2, q:"¿Quién es la heroína que sobrevive en 'Alien'?",
    ops:["Ellen Ripley","Sarah Connor","Laurie Strode","Clarice Starling"], ok:0,
    pista:"La interpreta Sigourney Weaver.", dato:"Se volvió un ícono de heroína de acción." },
  { cat:"terror", dif:2, q:"¿Qué película coreana de 2016 mezcla zombies y un tren a toda velocidad?",
    ops:["Train to Busan (Estación Zombie)","The Wailing","Kingdom","#Vivo"], ok:0,
    pista:"Los pasajeros huyen vagón por vagón.", dato:"Su título original es 'Busanhaeng'." },
  { cat:"terror", dif:3, q:"¿Qué película de Robert Eggers (2015) sigue a una familia puritana acosada por una bruja?",
    ops:["La bruja (The Witch)","La leyenda del jinete","El faro","Hereditary"], ok:0,
    pista:"Una cabra negra tiene un papel clave.", dato:"La cabra, 'Black Phillip', se volvió icónica." },
  { cat:"terror", dif:3, q:"¿Qué película de 1990 basada en Stephen King tiene a una fan que secuestra a su escritor favorito?",
    ops:["Misery","El resplandor","Carrie","Cementerio de animales"], ok:0,
    pista:"Una escena con un martillo es inolvidable.", dato:"Kathy Bates ganó el Oscar a Mejor Actriz." },
  { cat:"terror", dif:2, q:"¿Qué película de 1976 trata sobre una adolescente con telequinesis que se venga en su graduación?",
    ops:["Carrie","Christine","Ojos de fuego","La profecía"], ok:0,
    pista:"Le tiran sangre de cerdo en el baile.", dato:"La dirigió Brian De Palma, basada en Stephen King." },
  { cat:"terror", dif:3, q:"¿Qué película australiana de 2014 gira en torno a un libro infantil siniestro?",
    ops:["El Babadook","La luz del demonio","Insidious","Apaga la luz"], ok:0,
    pista:"'Mister Babadook' aparece en sus páginas.", dato:"Es el debut de la directora Jennifer Kent." },
  { cat:"terror", dif:3, q:"¿Qué película de Guillermo del Toro (2001) ocurre en un orfanato durante la Guerra Civil española?",
    ops:["El espinazo del diablo","El orfanato","El laberinto del fauno","Los otros"], ok:0,
    pista:"Una bomba sin explotar domina el patio.", dato:"Del Toro la considera 'hermana' de 'El laberinto del fauno'." },
  { cat:"terror", dif:3, q:"¿Qué película de 2001 con Nicole Kidman transcurre en una casa donde los hijos no toleran la luz?",
    ops:["Los otros","El orfanato","El sexto sentido","Insidious"], ok:0,
    pista:"Su giro final lo cambia todo.", dato:"La dirigió el español Alejandro Amenábar." },
  { cat:"terror", dif:2, q:"¿Qué película de 1999 de M. Night Shyamalan tiene a un niño que 've gente muerta'?",
    ops:["El sexto sentido","Los otros","Señales","La aldea"], ok:0,
    pista:"Bruce Willis es un psicólogo infantil.", dato:"'Veo gente muerta' es una de las frases más célebres del cine." },
  { cat:"terror", dif:2, q:"¿Qué comedia de terror de 2009 trae 'reglas para sobrevivir' a un apocalipsis zombi?",
    ops:["Zombieland (Tierra de zombies)","Shaun of the Dead","Scary Movie","Una noche en el museo"], ok:0,
    pista:"'Regla n.º1: cardio.'", dato:"Tiene un cameo muy recordado de Bill Murray." },
  { cat:"terror", dif:3, q:"¿Qué comedia británica de 2004 parodia a los zombies de Romero?",
    ops:["Shaun of the Dead","Zombieland","Scary Movie","Bienvenidos a Zombieland"], ok:0,
    pista:"La dirigió Edgar Wright con Simon Pegg.", dato:"Es la primera de la 'Trilogía del Cornetto'." },
  { cat:"terror", dif:2, q:"¿Qué saga tiene jóvenes que escapan de la muerte y luego mueren en accidentes elaborados?",
    ops:["Destino final","Saw","Cube","La profecía"], ok:0,
    pista:"El villano es la 'muerte' misma, invisible.", dato:"Cada película abre con un accidente catastrófico." },
  { cat:"terror", dif:3, q:"¿Qué película de Ari Aster (2019) ambienta su horror en un festival sueco a pleno sol?",
    ops:["Midsommar","La bruja","Hereditary","El ritual"], ok:0,
    pista:"Casi no hay escenas nocturnas.", dato:"Es del mismo director de 'Hereditary'." },

  /* --- Hollywood y Sagas --- */
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Jack Sparrow en 'Piratas del Caribe'?",
    ops:["Johnny Depp","Orlando Bloom","Geoffrey Rush","Javier Bardem"], ok:0,
    pista:"Se inspiró en un rockero para el personaje.", dato:"Lo basó en parte en Keith Richards." },
  { cat:"hollywood", dif:2, q:"En 'El Señor de los Anillos', ¿dónde hay que destruir el Anillo Único?",
    ops:["En el Monte del Destino","En Rivendel","En Mordor capital","En el río Anduin"], ok:0,
    pista:"Es un volcán en Mordor.", dato:"Solo el fuego donde fue forjado puede destruirlo." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Wolverine en las películas de los X-Men?",
    ops:["Hugh Jackman","Ryan Reynolds","Patrick Stewart","James McAvoy"], ok:0,
    pista:"Tiene garras de metal.", dato:"Interpretó el papel por más de 17 años." },
  { cat:"hollywood", dif:1, q:"¿Cuál es el nombre real de Spider-Man en las películas?",
    ops:["Peter Parker","Bruce Wayne","Clark Kent","Tony Stark"], ok:0,
    pista:"Es un estudiante de Nueva York.", dato:"'Un gran poder conlleva una gran responsabilidad'." },
  { cat:"hollywood", dif:1, q:"¿Qué actriz interpreta a Katniss Everdeen en 'Los juegos del hambre'?",
    ops:["Jennifer Lawrence","Shailene Woodley","Kristen Stewart","Emma Stone"], ok:0,
    pista:"Usa arco y flecha.", dato:"El papel la consagró como estrella mundial." },
  { cat:"hollywood", dif:1, q:"¿Qué saga sigue a un arqueólogo aventurero con sombrero y látigo?",
    ops:["Indiana Jones","La momia","Tomb Raider","National Treasure"], ok:0,
    pista:"Le teme a las serpientes.", dato:"Harrison Ford lo interpreta; Spielberg dirigió." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Han Solo en la trilogía original de Star Wars?",
    ops:["Harrison Ford","Mark Hamill","Liam Neeson","Ewan McGregor"], ok:0,
    pista:"Es el piloto del Halcón Milenario.", dato:"También es Indiana Jones." },
  { cat:"hollywood", dif:1, q:"En Star Wars, ¿quién resulta ser el padre de Luke Skywalker?",
    ops:["Darth Vader","Obi-Wan","El Emperador","Yoda"], ok:0,
    pista:"La gran revelación de 'El Imperio contraataca'.", dato:"'No, yo soy tu padre' es de las frases más citadas." },
  { cat:"hollywood", dif:2, q:"¿Qué metal ficticio sostiene la tecnología de Wakanda en 'Black Panther'?",
    ops:["Vibranium","Adamantium","Mithril","Kryptonita"], ok:0,
    pista:"El escudo del Capitán América es del mismo material.", dato:"Cayó a Wakanda en un meteorito." },
  { cat:"hollywood", dif:1, q:"¿Qué actriz interpreta a Black Widow (Natasha Romanoff) en Marvel?",
    ops:["Scarlett Johansson","Brie Larson","Elizabeth Olsen","Zoe Saldaña"], ok:0,
    pista:"Es una espía rusa reconvertida.", dato:"Tuvo su propia película en solitario en 2021." },
  { cat:"hollywood", dif:2, q:"¿Cómo se llama el martillo de Thor?",
    ops:["Mjölnir","Stormbreaker","Excalibur","Gungnir"], ok:0,
    pista:"Solo quien es 'digno' puede levantarlo.", dato:"En 'Endgame', el Capitán América logra alzarlo." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Neo en 'Matrix'?",
    ops:["Keanu Reeves","Tom Cruise","Will Smith","Brad Pitt"], ok:0,
    pista:"'El Elegido'.", dato:"También protagoniza la saga 'John Wick'." },
  { cat:"hollywood", dif:2, q:"¿Qué saga protagoniza Keanu Reeves como un asesino retirado que vuelve a la acción?",
    ops:["John Wick","Búsqueda implacable","El transportador","Jason Bourne"], ok:0,
    pista:"Todo empieza por la muerte de su perro.", dato:"Es famosa por su coreografía de peleas." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta al Capitán América en el Universo Marvel?",
    ops:["Chris Evans","Chris Hemsworth","Chris Pratt","Sebastian Stan"], ok:0,
    pista:"Lleva un escudo de vibranium.", dato:"Antes había interpretado a la Antorcha Humana." },
  { cat:"hollywood", dif:1, q:"En 'Misión: Imposible', ¿qué actor hace sus propias escenas de riesgo?",
    ops:["Tom Cruise","Matt Damon","Jason Statham","Daniel Craig"], ok:0,
    pista:"Se colgó de un avión despegando.", dato:"Interpreta a Ethan Hunt desde 1996." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpretó a James Bond en 'Casino Royale' (2006) y 'Skyfall'?",
    ops:["Daniel Craig","Pierce Brosnan","Sean Connery","Roger Moore"], ok:0,
    pista:"Fue el primer 007 rubio.", dato:"Se despidió del papel en 'Sin tiempo para morir'." },
  { cat:"hollywood", dif:3, q:"¿Quién compuso la música de 'El Rey León', 'Gladiador' e 'Interestelar'?",
    ops:["Hans Zimmer","John Williams","Howard Shore","Ennio Morricone"], ok:0,
    pista:"Es alemán y maneja sonidos electrónicos y orquesta.", dato:"Ganó el Oscar por 'El Rey León' y por 'Duna'." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Loki en el Universo Marvel?",
    ops:["Tom Hiddleston","Tom Holland","Benedict Cumberbatch","Andrew Garfield"], ok:0,
    pista:"Es el dios del engaño, hermano de Thor.", dato:"Su carisma le valió una serie propia." },
  { cat:"hollywood", dif:2, q:"¿Quién interpreta a Gandalf en 'El Señor de los Anillos'?",
    ops:["Ian McKellen","Christopher Lee","Liam Neeson","Patrick Stewart"], ok:0,
    pista:"'¡No puedes pasar!'", dato:"Christopher Lee, del mismo elenco, hizo de Saruman." },
  { cat:"hollywood", dif:1, q:"¿Qué villano morado busca las Gemas del Infinito en 'Avengers'?",
    ops:["Thanos","Ultron","Loki","Galactus"], ok:0,
    pista:"Con un chasquido borra media galaxia.", dato:"Lo interpreta Josh Brolin con captura de movimiento." },
  { cat:"hollywood", dif:3, q:"¿Quién dirigió 'Gladiador' (2000) y 'Alien' (1979)?",
    ops:["Ridley Scott","James Cameron","Michael Bay","Christopher Nolan"], ok:0,
    pista:"Es un maestro británico de la imagen.", dato:"Tiene una de las filmografías más amplias de Hollywood." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Doctor Strange en Marvel?",
    ops:["Benedict Cumberbatch","Tom Hiddleston","Mads Mikkelsen","Cillian Murphy"], ok:0,
    pista:"También fue Sherlock en una serie de la BBC.", dato:"Su personaje domina las artes místicas." },
  { cat:"hollywood", dif:3, q:"¿Qué película de Tarantino (2009) imagina un comando que caza nazis en la Segunda Guerra?",
    ops:["Bastardos sin gloria","Tiempos violentos","Kill Bill","Django sin cadenas"], ok:0,
    pista:"Termina con un cine en llamas.", dato:"Christoph Waltz ganó el Oscar por el coronel Hans Landa." },
  { cat:"hollywood", dif:1, q:"¿Qué saga tiene a Sarah Connor y un robot asesino enviado del futuro?",
    ops:["Terminator","RoboCop","Blade Runner","Matrix"], ok:0,
    pista:"'Volveré' ('I'll be back').", dato:"James Cameron la creó en 1984." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Thor en el Universo Marvel?",
    ops:["Chris Hemsworth","Chris Evans","Liam Hemsworth","Alexander Skarsgård"], ok:0,
    pista:"Es australiano y maneja un martillo.", dato:"Su hermano Liam también es actor." },

  /* --- Animación --- */
  { cat:"animacion", dif:1, q:"¿Qué princesa de Disney pierde una zapatilla de cristal a medianoche?",
    ops:["Cenicienta","Blancanieves","Aurora","Bella"], ok:0,
    pista:"Tiene un hada madrina y una calabaza.", dato:"Su película es de 1950." },
  { cat:"animacion", dif:2, q:"¿Cuál fue el primer largometraje animado de Disney (1937)?",
    ops:["Blancanieves y los siete enanitos","Pinocho","Fantasía","Bambi"], ok:0,
    pista:"Hay una manzana envenenada.", dato:"Fue el primer largometraje animado de Hollywood." },
  { cat:"animacion", dif:2, q:"En 'Aladdín' (1992), ¿quién pone la voz original del Genio?",
    ops:["Robin Williams","Eddie Murphy","Jim Carrey","Mike Myers"], ok:0,
    pista:"Era un comediante famoso por improvisar.", dato:"Improvisó tanto que se complicó nominarla al guion." },
  { cat:"animacion", dif:1, q:"¿Qué película de Pixar trata sobre un ratón que sueña con ser chef en París?",
    ops:["Ratatouille","Bichos","Soul","Luca"], ok:0,
    pista:"Cocina escondido bajo un gorro.", dato:"El crítico Anton Ego protagoniza una escena célebre." },
  { cat:"animacion", dif:2, q:"¿Qué película de Pixar (2020) viaja al 'más allá' y al mundo del jazz?",
    ops:["Soul","Intensa-Mente","Luca","Coco"], ok:0,
    pista:"Su protagonista es un profesor de música.", dato:"Ganó el Oscar a Mejor Película Animada." },
  { cat:"animacion", dif:1, q:"¿En qué película de Disney suena 'Hakuna Matata'?",
    ops:["El Rey León","El libro de la selva","Tarzán","Hércules"], ok:0,
    pista:"La cantan un suricato y un jabalí.", dato:"'Hakuna Matata' significa 'vive y sé feliz' en suajili." },
  { cat:"animacion", dif:2, q:"¿Qué estudio creó a los Minions, de 'Mi villano favorito'?",
    ops:["Illumination","DreamWorks","Pixar","Blue Sky"], ok:0,
    pista:"Son amarillos y hablan un idioma inventado.", dato:"También hizo 'Sing' y 'El Grinch'." },
  { cat:"animacion", dif:1, q:"¿Cómo se llama el villano de 'Mi villano favorito' que adopta a tres niñas?",
    ops:["Gru","Megamente","Lord Farquaad","Syndrome"], ok:0,
    pista:"Tiene un ejército de Minions.", dato:"Su voz original es de Steve Carell." },
  { cat:"animacion", dif:1, q:"¿Qué película de Pixar (2004) sigue a una familia de superhéroes?",
    ops:["Los Increíbles","Megamente","Big Hero 6","Sky High"], ok:0,
    pista:"El padre tiene súper fuerza; la madre, elasticidad.", dato:"La dirigió Brad Bird." },
  { cat:"animacion", dif:1, q:"¿Qué princesa polinesia navega el océano en una película de Disney de 2016?",
    ops:["Moana (Vaiana)","Elena","Raya","Pocahontas"], ok:0,
    pista:"La acompaña el semidiós Maui.", dato:"Dwayne 'The Rock' Johnson hace la voz de Maui." },
  { cat:"animacion", dif:2, q:"¿Qué película de Studio Ghibli (1988) muestra a dos hermanas y un gato-autobús?",
    ops:["Mi vecino Totoro","La princesa Mononoke","El castillo ambulante","Ponyo"], ok:0,
    pista:"Su criatura peluda es el logo del estudio.", dato:"Es de las películas más queridas de Miyazaki." },
  { cat:"animacion", dif:1, q:"¿Cómo se llama el muñeco de nieve de 'Frozen'?",
    ops:["Olaf","Sven","Kristoff","Marshmallow"], ok:0,
    pista:"Sueña con conocer el verano.", dato:"Aporta el humor de la película." },
  { cat:"animacion", dif:2, q:"¿Qué película stop-motion de Tim Burton (1993) cruza Halloween y Navidad?",
    ops:["El extraño mundo de Jack","El cadáver de la novia","Coraline","Frankenweenie"], ok:0,
    pista:"Su protagonista es Jack Skellington.", dato:"Está hecha cuadro a cuadro con muñecos." },
  { cat:"animacion", dif:3, q:"¿Qué película stop-motion de 2009 tiene una 'otra madre' con botones por ojos?",
    ops:["Coraline","ParaNorman","Los Boxtrolls","El extraño mundo de Jack"], ok:0,
    pista:"Está basada en un libro de Neil Gaiman.", dato:"La dirigió Henry Selick, del estudio Laika." },
  { cat:"animacion", dif:1, q:"¿Qué saga de DreamWorks sigue a un panda torpe que se vuelve guerrero del kung-fu?",
    ops:["Kung Fu Panda","Madagascar","Shrek","Rio"], ok:0,
    pista:"El panda se llama Po.", dato:"Jack Black le pone la voz en inglés." },
  { cat:"animacion", dif:1, q:"¿Qué película de DreamWorks tiene a un vikingo y su dragón Desdentado?",
    ops:["Cómo entrenar a tu dragón","Brave","Rio","Epic"], ok:0,
    pista:"El protagonista se llama Hipo.", dato:"Es elogiada por sus escenas de vuelo." },
  { cat:"animacion", dif:1, q:"En 'Buscando a Nemo', ¿cómo se llama la pez azul olvidadiza?",
    ops:["Dory","Perla","Coral","Destiny"], ok:0,
    pista:"Repite 'sigue nadando'.", dato:"Tuvo su propia película, 'Buscando a Dory'." },
  { cat:"animacion", dif:2, q:"¿Qué película animada de 2018 sobre Spider-Man y el multiverso ganó el Oscar?",
    ops:["Spider-Man: Un nuevo universo","Los Increíbles 2","Ralph rompe Internet","Hotel Transilvania"], ok:0,
    pista:"Su protagonista es Miles Morales.", dato:"Su estilo visual cambió la animación moderna." },
  { cat:"animacion", dif:3, q:"¿Qué película de Disney de 1991 fue la primera animada nominada al Oscar a Mejor Película?",
    ops:["La bella y la bestia","El Rey León","Aladdín","La sirenita"], ok:0,
    pista:"Una rosa encantada marca el tiempo.", dato:"Logró esa nominación histórica en la ceremonia de 1992." },
  { cat:"animacion", dif:1, q:"¿Qué sirena sueña con vivir en la superficie en la película de Disney de 1989?",
    ops:["Ariel (La sirenita)","Moana","Esmeralda","Pocahontas"], ok:0,
    pista:"Hace un trato con la bruja Úrsula.", dato:"Marcó el inicio del 'Renacimiento de Disney'." },
  { cat:"animacion", dif:3, q:"¿Qué película de Miyazaki (1997) trata sobre bosques, dioses y una guerrera?",
    ops:["La princesa Mononoke","El viaje de Chihiro","Nausicaä","Ponyo"], ok:0,
    pista:"Su heroína cabalga un lobo gigante.", dato:"Fue un fenómeno de taquilla en Japón." },
  { cat:"animacion", dif:3, q:"¿Qué película argentina animada de Campanella (2013) está basada en un cuento de Fontanarrosa sobre el metegol?",
    ops:["Metegol","Patoruzito","Gaturro","El arca"], ok:0,
    pista:"Los muñecos del metegol cobran vida.", dato:"Ganó el Goya y el Cóndor de Plata a mejor animación." },

  /* --- Cine Argentino y Latino --- */
  { cat:"argentino", dif:3, q:"¿Qué película de Pablo Trapero (2015) retrata a la familia Puccio, secuestradores reales?",
    ops:["El Clan","Carancho","Leonera","El bonaerense"], ok:0,
    pista:"Una familia 'normal' que esconde un horror.", dato:"Guillermo Francella interpreta a Arquímedes Puccio." },
  { cat:"argentino", dif:3, q:"¿Qué comedia argentina de 1985 sobre un velorio familiar es de culto?",
    ops:["Esperando la carroza","Pizza, birra, faso","Esperando la luz","Made in Argentina"], ok:0,
    pista:"'¿Mamá comió?'", dato:"Sus frases se citan hasta hoy." },
  { cat:"argentino", dif:3, q:"¿Qué road movie de 2004 sigue al joven Che Guevara recorriendo Sudamérica?",
    ops:["Diarios de motocicleta","También la lluvia","Machuca","El Che"], ok:0,
    pista:"La dirigió el brasileño Walter Salles.", dato:"Gael García Bernal interpreta al Che." },
  { cat:"argentino", dif:3, q:"¿Qué película mexicana de Alfonso Cuarón (2001) sigue a dos amigos y una mujer en un viaje?",
    ops:["Y tu mamá también","Amores perros","Roma","Como agua para chocolate"], ok:0,
    pista:"Lanzó a Gael García Bernal y Diego Luna.", dato:"Fue un éxito internacional inesperado." },
  { cat:"argentino", dif:3, q:"¿Qué película de Iñárritu (2000) entrelaza tres historias y una pelea de perros en Ciudad de México?",
    ops:["Amores perros","21 gramos","Babel","Biutiful"], ok:0,
    pista:"Su título habla de perros.", dato:"Fue nominada al Oscar a Mejor Película Extranjera." },
  { cat:"argentino", dif:2, q:"¿Qué película de Guillermo del Toro (2006) cruza la Guerra Civil española con un fauno y un laberinto?",
    ops:["El laberinto del fauno","El espinazo del diablo","La forma del agua","El orfanato"], ok:0,
    pista:"Una niña entra en un mundo de fantasía oscura.", dato:"Ganó 3 Oscars técnicos." },
  { cat:"argentino", dif:2, q:"¿Qué película argentina con Darín (2019) recrea un golpe para recuperar ahorros tras el corralito?",
    ops:["La odisea de los giles","El robo del siglo","Plata dulce","Tesis sobre un homicidio"], ok:0,
    pista:"Un pueblo entero se une para la 'venganza'.", dato:"Está basada en una novela de Eduardo Sacheri." },
  { cat:"argentino", dif:2, q:"¿Qué película argentina (2020) recrea el 'robo del siglo' al Banco Río de Acassuso?",
    ops:["El robo del siglo","La odisea de los giles","El Aura","Nueve reinas"], ok:0,
    pista:"Salieron por un túnel sin que los atraparan en el acto.", dato:"El robo real ocurrió en 2006." },
  { cat:"argentino", dif:3, q:"¿Qué directora argentina hizo 'La ciénaga' y 'Zama'?",
    ops:["Lucrecia Martel","María Luisa Bemberg","Lucía Puenzo","Anahí Berneri"], ok:0,
    pista:"Es referente del 'Nuevo Cine Argentino'.", dato:"Su cine es famoso por el uso del sonido." },
  { cat:"argentino", dif:3, q:"¿Qué película chilena de Sebastián Lelio ganó el Oscar extranjero en 2018?",
    ops:["Una mujer fantástica","No","Gloria","Machuca"], ok:0,
    pista:"Su protagonista es una mujer trans.", dato:"Daniela Vega es la protagonista." },
  { cat:"argentino", dif:3, q:"¿Qué comedia argentina (2011) tiene a Darín como un ferretero amargado y un chino perdido?",
    ops:["Un cuento chino","Tiempo de valientes","Luna de Avellaneda","El mismo amor, la misma lluvia"], ok:0,
    pista:"Cae una vaca del cielo.", dato:"La dirigió Sebastián Borensztein." },
  { cat:"argentino", dif:3, q:"¿Qué película brasileña de 1998 sobre una mujer y un niño buscando a su padre fue nominada al Oscar?",
    ops:["Estación Central","Ciudad de Dios","Tropa de élite","El payaso"], ok:0,
    pista:"Su título original es 'Central do Brasil'.", dato:"Fernanda Montenegro fue nominada a Mejor Actriz." },

  /* --- Mix de Cine --- */
  { cat:"mixto", dif:2, q:"¿Qué clásico de 1939 sigue a Dorothy por un camino de baldosas amarillas?",
    ops:["El mago de Oz","Lo que el viento se llevó","Cantando bajo la lluvia","Blancanieves"], ok:0,
    pista:"'Ya no estamos en Kansas'.", dato:"Pasó del blanco y negro al color para impactar." },
  { cat:"mixto", dif:3, q:"¿Qué película muda de 1936 de Charles Chaplin critica la era industrial?",
    ops:["Tiempos modernos","El gran dictador","Luces de la ciudad","El chico"], ok:0,
    pista:"Chaplin queda atrapado en los engranajes.", dato:"Es de sus últimas películas casi mudas." },
  { cat:"mixto", dif:2, q:"¿Qué actriz ganó el Oscar por 'La La Land' (2016)?",
    ops:["Emma Stone","Emma Watson","Natalie Portman","Margot Robbie"], ok:0,
    pista:"Ryan Gosling la coprotagoniza.", dato:"La película casi gana Mejor Película por un famoso error en el sobre." },
  { cat:"mixto", dif:2, q:"¿Qué frase dice Forrest Gump sobre la vida?",
    ops:["'La vida es como una caja de bombones'","'Que la fuerza te acompañe'","'Sayonara, baby'","'Houston, tenemos un problema'"], ok:0,
    pista:"Habla de dulces y de lo impredecible.", dato:"'Nunca sabés qué te va a tocar'." },
  { cat:"mixto", dif:3, q:"¿De qué película es la frase '¿Estás hablando conmigo?' (You talkin' to me?)?",
    ops:["Taxi Driver","El Padrino","Buenos muchachos","Tiempos violentos"], ok:0,
    pista:"Un taxista solitario se habla al espejo.", dato:"Robert De Niro la improvisó; la dirigió Scorsese." },
  { cat:"mixto", dif:2, q:"¿Qué director hizo 'Buenos muchachos', 'Taxi Driver' y 'El lobo de Wall Street'?",
    ops:["Martin Scorsese","Francis Ford Coppola","Brian De Palma","Quentin Tarantino"], ok:0,
    pista:"Trabajó muchas veces con De Niro y DiCaprio.", dato:"Ganó el Oscar a Mejor Director por 'Los infiltrados'." },
  { cat:"mixto", dif:2, q:"¿Qué actor protagoniza 'El lobo de Wall Street' como Jordan Belfort?",
    ops:["Leonardo DiCaprio","Christian Bale","Matthew McConaughey","Brad Pitt"], ok:0,
    pista:"Lo dirigió Scorsese.", dato:"McConaughey tiene un cameo muy recordado al inicio." },
  { cat:"mixto", dif:2, q:"¿Qué película ganó el Oscar a Mejor Película (2023) con multiversos y 'todo a la vez'?",
    ops:["Todo en todas partes al mismo tiempo","Coda","Nomadland","Green Book"], ok:0,
    pista:"Una lavandería, impuestos y universos paralelos.", dato:"Michelle Yeoh ganó Mejor Actriz." },
  { cat:"mixto", dif:1, q:"¿Qué película biográfica de 2023 sobre el 'padre de la bomba atómica' dirigió Christopher Nolan?",
    ops:["Oppenheimer","Dunkerque","Tenet","El truco final"], ok:0,
    pista:"Se estrenó el mismo día que 'Barbie'.", dato:"Ganó el Oscar a Mejor Película." },
  { cat:"mixto", dif:1, q:"¿Qué película rosa de 2023 de Greta Gerwig batió récords de taquilla?",
    ops:["Barbie","Wonka","Súper Mario Bros","Elemental"], ok:0,
    pista:"Margot Robbie y Ryan Gosling la protagonizan.", dato:"Su estreno se asoció al fenómeno 'Barbenheimer'." },
  { cat:"mixto", dif:2, q:"¿Qué película ochentosa (1985) sigue a unos amigos buscando un tesoro pirata?",
    ops:["Los Goonies","Cuenta conmigo","Exploradores","E.T."], ok:0,
    pista:"Hay un mapa y un personaje llamado 'Sloth'.", dato:"Su guion lo escribió Steven Spielberg." },
  { cat:"mixto", dif:2, q:"¿Quién dirigió 'El Padrino' (1972)?",
    ops:["Francis Ford Coppola","Martin Scorsese","Sergio Leone","Brian De Palma"], ok:0,
    pista:"También hizo 'Apocalipsis Now'.", dato:"La película relanzó la carrera de Marlon Brando." },

  /* ===================== TANDA 3 (+100 preguntas) ===================== */

  /* --- Terror y Slasher --- */
  { cat:"terror", dif:2, q:"¿Qué película de 1982 producida por Spielberg tiene una casa embrujada y la frase 'Ya están aquí'?",
    ops:["Poltergeist","Amityville","Insidious","La entidad"], ok:0,
    pista:"Una nena habla con un televisor lleno de estática.", dato:"La dirigió Tobe Hooper, el de 'La masacre de Texas'." },
  { cat:"terror", dif:2, q:"¿En qué película de 2018 las criaturas cazan por el sonido y hay que vivir en silencio?",
    ops:["Un lugar en silencio","Bird Box","El aro","No respires"], ok:0,
    pista:"John Krasinski la dirige y actúa con Emily Blunt.", dato:"Casi no tiene diálogos hablados." },
  { cat:"terror", dif:2, q:"¿Qué película de 2002 gira en torno a una cinta de video maldita que mata en 7 días?",
    ops:["El aro (The Ring)","La huérfana","Sinister","Llamada perdida"], ok:0,
    pista:"Es la remake del japonés 'Ringu'.", dato:"La niña del pozo se llama Samara." },
  { cat:"terror", dif:3, q:"¿Qué película de 2002 de Danny Boyle reinventó a los 'infectados' rápidos?",
    ops:["28 días después","Guerra Mundial Z","REC","La purga"], ok:0,
    pista:"Londres aparece completamente vacío.", dato:"Influyó en casi todo el cine de zombies posterior." },
  { cat:"terror", dif:3, q:"¿Qué villano aparece si decís su nombre 5 veces frente al espejo (película de 1992)?",
    ops:["Candyman","Bloody Mary","Pennywise","El Coco"], ok:0,
    pista:"Tiene un garfio por mano.", dato:"Tuvo una nueva versión producida por Jordan Peele en 2021." },
  { cat:"terror", dif:3, q:"¿Qué saga de terror de Clive Barker tiene al demonio 'Pinhead' y un cubo que abre el infierno?",
    ops:["Hellraiser","Hellboy","La profecía","El exorcista"], ok:0,
    pista:"Resolver el cubo invoca a los Cenobitas.", dato:"Pinhead tiene clavos clavados en toda la cabeza." },
  { cat:"terror", dif:3, q:"¿Qué película de bajo presupuesto de Sam Raimi (1981) tiene a unos jóvenes y un libro de los muertos en una cabaña?",
    ops:["Posesión infernal (Evil Dead)","La cabaña del terror","Bosque maldito","Cabin Fever"], ok:0,
    pista:"Su héroe es Ash, con una motosierra por mano.", dato:"Raimi luego dirigió las películas de Spider-Man." },
  { cat:"terror", dif:3, q:"¿Qué película de 1976 trata sobre Damien, un niño que sería el Anticristo?",
    ops:["La profecía (The Omen)","El exorcista","El bebé de Rosemary","Carrie"], ok:0,
    pista:"El número 666 es clave.", dato:"Su banda sonora ganó el Oscar." },
  { cat:"terror", dif:3, q:"¿Qué clásico italiano de Dario Argento (1977) transcurre en una academia de ballet con brujas?",
    ops:["Suspiria","Profondo Rosso","Phenomena","Inferno"], ok:0,
    pista:"Famosa por sus colores rojos y verdes intensos.", dato:"Tuvo una nueva versión en 2018 con Tilda Swinton." },
  { cat:"terror", dif:2, q:"¿Qué actor de terror clásico interpretó al monstruo en 'Frankenstein' (1931)?",
    ops:["Boris Karloff","Bela Lugosi","Lon Chaney","Vincent Price"], ok:0,
    pista:"Tornillos en el cuello y andar rígido.", dato:"Bela Lugosi, en cambio, fue el Drácula de 1931." },
  { cat:"terror", dif:2, q:"¿Qué clásico de Hitchcock (1963) muestra un pueblo atacado por aves?",
    ops:["Los pájaros","Psicosis","Vértigo","La ventana indiscreta"], ok:0,
    pista:"No tiene música, solo sonidos de aves.", dato:"Basada en un relato de Daphne du Maurier." },
  { cat:"terror", dif:2, q:"En 'Gremlins' (1984), ¿qué regla NO hay que romper?",
    ops:["No mojarlos","No mirarlos","No hablarles","No nombrarlos"], ok:0,
    pista:"También: nada de comida después de medianoche.", dato:"Mojarlos hace que se multipliquen." },
  { cat:"terror", dif:3, q:"¿Qué película de Stephen King tiene la frase 'a veces, la muerte es mejor', sobre un cementerio que revive mascotas?",
    ops:["Cementerio de animales","It","Cujo","Christine"], ok:0,
    pista:"Su título en inglés es 'Pet Sematary'.", dato:"El terreno indígena trae de vuelta a los muertos... cambiados." },
  { cat:"terror", dif:3, q:"¿Qué película de 2007 de Frank Darabont (de Stephen King) atrapa a un pueblo bajo una niebla con criaturas?",
    ops:["La niebla (The Mist)","Silent Hill","The Fog","Bird Box"], ok:0,
    pista:"Tiene uno de los finales más desoladores del terror.", dato:"Se refugian en un supermercado." },
  { cat:"terror", dif:2, q:"¿Qué película de 1994 tiene a Tom Cruise y Brad Pitt como vampiros?",
    ops:["Entrevista con el vampiro","Drácula de Bram Stoker","Crepúsculo","Blade"], ok:0,
    pista:"Basada en una novela de Anne Rice.", dato:"Una jovencísima Kirsten Dunst interpreta a una niña vampira." },
  { cat:"terror", dif:3, q:"¿Qué versión de 'Drácula' (1992) dirigió Francis Ford Coppola?",
    ops:["Drácula de Bram Stoker","Nosferatu","Drácula de Hammer","Van Helsing"], ok:0,
    pista:"Gary Oldman interpreta al conde.", dato:"Ganó 3 Oscars técnicos." },
  { cat:"terror", dif:3, q:"¿Qué película sueca de 2008 muestra la amistad entre un niño y una vampira?",
    ops:["Déjame entrar","Thelma","The Wailing","Border"], ok:0,
    pista:"Su título original es 'Låt den rätte komma in'.", dato:"Tuvo una remake de Hollywood, 'Let Me In'." },
  { cat:"terror", dif:2, q:"¿Qué película de Tim Burton (1999) tiene a Johnny Depp investigando a un jinete sin cabeza?",
    ops:["La leyenda del jinete sin cabeza (Sleepy Hollow)","El cadáver de la novia","Sombras tenebrosas","El secreto de la pirámide"], ok:0,
    pista:"Christopher Walken hace del jinete.", dato:"Ganó el Oscar a Mejor Dirección de Arte." },
  { cat:"terror", dif:2, q:"¿Qué saga (desde 2013) imagina una noche al año en la que todos los crímenes son legales?",
    ops:["La purga","Saw","Los extraños","Escape Room"], ok:0,
    pista:"Las familias se atrincheran en sus casas.", dato:"Nació como un thriller de bajo presupuesto y se volvió franquicia." },
  { cat:"terror", dif:2, q:"¿Qué película de 2022 sigue una maldición que se transmite a través de una sonrisa siniestra?",
    ops:["Smile","Talk to Me","Barbarian","Megan"], ok:0,
    pista:"Una psiquiatra empieza a ver gente sonriendo de forma macabra.", dato:"Su marketing puso 'sonrientes' inquietantes en eventos en vivo." },
  { cat:"terror", dif:3, q:"¿Qué película de 2021 tiene a un secuestrador enmascarado llamado 'El Agarrador' (Ethan Hawke)?",
    ops:["Black Phone","Hush","El hombre invisible","La huérfana"], ok:0,
    pista:"Un teléfono desconectado empieza a sonar en un sótano.", dato:"Está basada en un cuento de Joe Hill, hijo de Stephen King." },
  { cat:"terror", dif:3, q:"¿Qué película australiana de 2023 usa una mano embalsamada para contactar espíritus?",
    ops:["Háblame (Talk to Me)","The Babadook","Relic","Lake Mungo"], ok:0,
    pista:"'Te hablo' y 'te dejo entrar' son las reglas del juego.", dato:"Se volvió un éxito sorpresa del estudio A24." },
  { cat:"terror", dif:3, q:"¿Qué película de Robert Eggers (2019) encierra a dos fareros que enloquecen?",
    ops:["El faro","La bruja","Nosferatu","Men"], ok:0,
    pista:"Está filmada en blanco y negro, casi cuadrada.", dato:"Robert Pattinson y Willem Dafoe la protagonizan." },
  { cat:"terror", dif:2, q:"¿Qué película de zombies de 2013 con Brad Pitt muestra una pandemia global?",
    ops:["Guerra Mundial Z","28 semanas después","Soy leyenda","Contagio"], ok:0,
    pista:"Los zombies trepan unos sobre otros como hormigas.", dato:"Basada (libremente) en la novela de Max Brooks." },
  { cat:"terror", dif:3, q:"¿Qué película de 2014 sigue una maldición que 'te persigue' caminando y se transmite por contacto?",
    ops:["It Follows","The Ring","Sé lo que hicieron...","Oculus"], ok:0,
    pista:"La entidad puede tomar la forma de cualquiera.", dato:"Su estética ochentosa la volvió de culto." },
  { cat:"terror", dif:2, q:"¿Qué slasher de 1997 persigue a unos jóvenes con un pescador del garfio?",
    ops:["Sé lo que hicieron el verano pasado","Leyenda urbana","Halloween H20","Cherry Falls"], ok:0,
    pista:"Tras un accidente, los acosa una nota: 'Sé lo que hicieron'.", dato:"La escribió Kevin Williamson, el mismo guionista de 'Scream'." },

  /* --- Hollywood y Sagas --- */
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Lord Voldemort en 'Harry Potter'?",
    ops:["Ralph Fiennes","Gary Oldman","Jason Isaacs","Alan Rickman"], ok:0,
    pista:"El villano sin nariz, 'El que no debe ser nombrado'.", dato:"Alan Rickman, en cambio, interpreta a Snape." },
  { cat:"hollywood", dif:2, q:"¿Qué personaje le ofrece a Neo la píldora roja en 'Matrix'?",
    ops:["Morfeo","Trinity","Cypher","El Oráculo"], ok:0,
    pista:"Lo interpreta Laurence Fishburne.", dato:"Su nombre viene del dios griego de los sueños." },
  { cat:"hollywood", dif:1, q:"¿Qué parque temático cobra vida con dinosaurios clonados a partir de ADN en ámbar?",
    ops:["Jurassic Park","Westworld","Isla Calavera","Pandora"], ok:0,
    pista:"'La vida se abre camino.'", dato:"Sus efectos de 1993 fueron revolucionarios." },
  { cat:"hollywood", dif:2, q:"¿Qué dos hermanos dirigieron 'Avengers: Infinity War' y 'Endgame'?",
    ops:["Los hermanos Russo","Las hermanas Wachowski","Los hermanos Coen","Los hermanos Nolan"], ok:0,
    pista:"Antes hicieron 'Capitán América: Winter Soldier'.", dato:"Cerraron la 'Saga del Infinito' de Marvel." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Star-Lord en 'Guardianes de la Galaxia'?",
    ops:["Chris Pratt","Chris Evans","Chris Pine","Chris Hemsworth"], ok:0,
    pista:"Su nave suena con un walkman de los 80.", dato:"Antes era conocido por la comedia 'Parks and Recreation'." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Deadpool, el mercenario bocón?",
    ops:["Ryan Reynolds","Ryan Gosling","Hugh Jackman","Chris Pratt"], ok:0,
    pista:"Rompe la 'cuarta pared' y habla a la cámara.", dato:"Impulsó él mismo el proyecto durante años." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Frodo en 'El Señor de los Anillos'?",
    ops:["Elijah Wood","Orlando Bloom","Sean Astin","Daniel Radcliffe"], ok:0,
    pista:"Es el hobbit que carga el Anillo.", dato:"Sean Astin interpreta a su fiel amigo Sam." },
  { cat:"hollywood", dif:3, q:"¿Qué actor da vida (por captura de movimiento) a Gollum?",
    ops:["Andy Serkis","Doug Jones","Mark Ruffalo","Benedict Cumberbatch"], ok:0,
    pista:"'Mi tesoro...'", dato:"Es pionero de la actuación por captura de movimiento." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Edward, el vampiro de la saga 'Crepúsculo'?",
    ops:["Robert Pattinson","Taylor Lautner","Robert Downey Jr.","Ian Somerhalder"], ok:0,
    pista:"Años después sería Batman.", dato:"Brilla al sol en vez de quemarse." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Batman en 'The Batman' (2022)?",
    ops:["Robert Pattinson","Ben Affleck","Christian Bale","Michael Keaton"], ok:0,
    pista:"La dirigió Matt Reeves.", dato:"Es una versión más detectivesca y oscura del personaje." },
  { cat:"hollywood", dif:1, q:"¿Qué actriz interpreta a la Mujer Maravilla en el cine de DC?",
    ops:["Gal Gadot","Scarlett Johansson","Brie Larson","Margot Robbie"], ok:0,
    pista:"Tiene un lazo de la verdad.", dato:"La actriz es israelí." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Aquaman en el cine de DC?",
    ops:["Jason Momoa","Henry Cavill","Chris Hemsworth","Dwayne Johnson"], ok:0,
    pista:"Es el rey de la Atlántida.", dato:"Antes fue Khal Drogo en 'Game of Thrones'." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Superman en 'El hombre de acero' (2013)?",
    ops:["Henry Cavill","Brandon Routh","Tom Welling","Tyler Hoechlin"], ok:0,
    pista:"También es Geralt en 'The Witcher'.", dato:"El clásico Superman de 1978 fue Christopher Reeve." },
  { cat:"hollywood", dif:3, q:"¿Quién dirigió 'Mad Max: Furia en el camino' (2015)?",
    ops:["George Miller","Zack Snyder","Denis Villeneuve","Michael Bay"], ok:0,
    pista:"Creó la saga Mad Max desde 1979.", dato:"La película ganó 6 Oscars técnicos." },
  { cat:"hollywood", dif:1, q:"¿Qué saga de acción tiene a John McClane atrapado en un rascacielos en Navidad?",
    ops:["Duro de matar (Die Hard)","Comando","Máxima velocidad","El protegido"], ok:0,
    pista:"'Yippee-ki-yay'.", dato:"Bruce Willis se consagró como héroe de acción." },
  { cat:"hollywood", dif:1, q:"¿Qué actor protagoniza 'Top Gun' (1986) y su secuela 'Maverick' (2022)?",
    ops:["Tom Cruise","Val Kilmer","Brad Pitt","Tom Hanks"], ok:0,
    pista:"Vuela cazas y maneja motos.", dato:"En la secuela pilotó aviones de verdad para las tomas." },
  { cat:"hollywood", dif:2, q:"¿Qué actor escribió y protagonizó 'Rocky' (1976)?",
    ops:["Sylvester Stallone","Arnold Schwarzenegger","Robert De Niro","Burt Reynolds"], ok:0,
    pista:"Un boxeador de Filadelfia sube escalones.", dato:"La película ganó el Oscar a Mejor Película." },
  { cat:"hollywood", dif:2, q:"¿Qué película de 1995 protagonizó y dirigió Mel Gibson, sobre William Wallace?",
    ops:["Corazón valiente (Braveheart)","Gladiador","El patriota","Rob Roy"], ok:0,
    pista:"'¡Libertad!'", dato:"Ganó 5 Oscars, incluido Mejor Película." },
  { cat:"hollywood", dif:2, q:"¿Qué actor protagoniza 'Interestelar' (2014) como el piloto Cooper?",
    ops:["Matthew McConaughey","Brad Pitt","Ryan Gosling","Jake Gyllenhaal"], ok:0,
    pista:"Viaja por un agujero de gusano para salvar a la humanidad.", dato:"La dirigió Christopher Nolan." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Kylo Ren en la nueva trilogía de Star Wars?",
    ops:["Adam Driver","Oscar Isaac","Domhnall Gleeson","John Boyega"], ok:0,
    pista:"Es nieto de Darth Vader.", dato:"Su sable de luz tiene una empuñadura cruzada." },
  { cat:"hollywood", dif:2, q:"¿Qué actor interpreta a Obi-Wan Kenobi en las precuelas de Star Wars?",
    ops:["Ewan McGregor","Liam Neeson","Hayden Christensen","Samuel L. Jackson"], ok:0,
    pista:"De joven fue maestro de Anakin.", dato:"Retomó el papel en una serie de Disney+." },
  { cat:"hollywood", dif:2, q:"¿Qué película de 2006 de Zack Snyder retrata a 300 espartanos en la batalla de las Termópilas?",
    ops:["300","Troya","Gladiador","Furia de titanes"], ok:0,
    pista:"'¡Esto es Esparta!'", dato:"Está basada en un cómic de Frank Miller." },
  { cat:"hollywood", dif:3, q:"¿Qué película de Nolan (2006) enfrenta a dos magos rivales obsesionados con un truco?",
    ops:["El gran truco (The Prestige)","El ilusionista","Ahora me ves","Memento"], ok:0,
    pista:"Hugh Jackman y Christian Bale la protagonizan.", dato:"David Bowie interpreta al inventor Nikola Tesla." },
  { cat:"hollywood", dif:1, q:"¿Quién dirigió 'King Kong' (2005) y la trilogía de 'El Señor de los Anillos'?",
    ops:["Peter Jackson","James Cameron","Guillermo del Toro","Robert Zemeckis"], ok:0,
    pista:"Es neozelandés.", dato:"Volvió al cine de monstruos tras conquistar la Tierra Media." },
  { cat:"hollywood", dif:1, q:"¿Qué actor interpreta a Harry Potter en las películas?",
    ops:["Daniel Radcliffe","Rupert Grint","Elijah Wood","Tom Felton"], ok:0,
    pista:"Tiene una cicatriz con forma de rayo.", dato:"Hizo el papel desde los 11 hasta los 21 años." },

  /* --- Animación --- */
  { cat:"animacion", dif:1, q:"¿Cuál es la frase famosa de Buzz Lightyear en 'Toy Story'?",
    ops:["'Al infinito y más allá'","'Hay una serpiente en mi bota'","'Yo soy tu padre'","'Hakuna Matata'"], ok:0,
    pista:"Es un guardián espacial de juguete.", dato:"Tim Allen le pone la voz en inglés." },
  { cat:"animacion", dif:1, q:"En 'Monsters Inc.', ¿cómo se llama la niña que se cuela al mundo de los monstruos?",
    ops:["Boo","Riley","Vanellope","Agnes"], ok:0,
    pista:"Sully y Mike la cuidan.", dato:"Descubren que la risa da más energía que el miedo." },
  { cat:"animacion", dif:1, q:"¿Cómo se llama el auto rojo de carreras protagonista de 'Cars'?",
    ops:["Rayo McQueen","Mate","Doc Hudson","Francesco"], ok:0,
    pista:"Aprende humildad en el pueblo Radiador Springs.", dato:"Su número es el 95." },
  { cat:"animacion", dif:2, q:"¿Qué película de Pixar (2012) tiene a la princesa Mérida y se ambienta en Escocia?",
    ops:["Valiente (Brave)","Enredados","Vaiana","Frozen"], ok:0,
    pista:"Mérida es experta con el arco.", dato:"Ganó el Oscar a Mejor Película Animada." },
  { cat:"animacion", dif:2, q:"¿En qué país se ambienta la película de Pixar 'Luca' (2021)?",
    ops:["Italia","Grecia","España","México"], ok:0,
    pista:"En la Riviera, con monstruos marinos.", dato:"'Silenzio, Bruno' es su frase clave." },
  { cat:"animacion", dif:2, q:"En 'Red' (Turning Red, 2022), ¿en qué se transforma la protagonista cuando se emociona?",
    ops:["Un panda rojo gigante","Un dragón","Un gato","Un lobo"], ok:0,
    pista:"Le pasa por una herencia familiar.", dato:"Se ambienta en Toronto, a comienzos de los 2000." },
  { cat:"animacion", dif:1, q:"¿Qué princesa de Disney tiene un pelo larguísimo y mágico en 'Enredados'?",
    ops:["Rapunzel","Ariel","Mérida","Tiana"], ok:0,
    pista:"Vive encerrada en una torre.", dato:"Su pelo brilla al cantar." },
  { cat:"animacion", dif:2, q:"En 'Ralph el demoledor', ¿de dónde 'escapa' el protagonista?",
    ops:["De un videojuego arcade","De un parque de diversiones","De una juguetería","De un circo"], ok:0,
    pista:"Es el villano de un juego de los 80.", dato:"Quiere demostrar que puede ser un héroe." },
  { cat:"animacion", dif:2, q:"En 'Zootopia' (2016), ¿qué animal es la policía protagonista, Judy Hopps?",
    ops:["Una coneja","Una zorra","Una loba","Una gata"], ok:0,
    pista:"Se asocia con un zorro estafador.", dato:"Ganó el Oscar a Mejor Película Animada." },
  { cat:"animacion", dif:2, q:"¿Qué película de Disney (1998) sigue a una joven china que se hace pasar por soldado?",
    ops:["Mulán","Pocahontas","Brave","Raya"], ok:0,
    pista:"La acompaña el dragón Mushu.", dato:"Se basa en una antigua leyenda china." },
  { cat:"animacion", dif:2, q:"En 'Las locuras del emperador', ¿en qué se convierte el emperador Kuzco?",
    ops:["En una llama","En un sapo","En un burro","En un cuervo"], ok:0,
    pista:"Una poción de Yzma falla.", dato:"Es una de las comedias más queridas de Disney." },
  { cat:"animacion", dif:1, q:"En 'Lilo & Stitch', ¿qué es realmente Stitch?",
    ops:["Un experimento alienígena","Un perro raro","Un robot","Un koala"], ok:0,
    pista:"Su código es 'Experimento 626'.", dato:"'Ohana significa familia.'" },
  { cat:"animacion", dif:2, q:"¿Qué clásico de Disney (1942) tiene a un cervatillo cuya madre muere?",
    ops:["Bambi","Dumbo","El Rey León","El zorro y el sabueso"], ok:0,
    pista:"Sus amigos son Tambor y Flor.", dato:"La muerte de la madre es de las escenas más recordadas de Disney." },
  { cat:"animacion", dif:1, q:"¿Qué elefantito de Disney puede volar usando sus enormes orejas?",
    ops:["Dumbo","Bambi","Manny","Horton"], ok:0,
    pista:"Una pluma le da 'confianza'.", dato:"Tuvo una versión en acción real de Tim Burton en 2019." },
  { cat:"animacion", dif:2, q:"¿Qué ardilla persigue eternamente una bellota en la saga 'La era de hielo'?",
    ops:["Scrat","Sid","Diego","Manny"], ok:0,
    pista:"Nunca logra atraparla.", dato:"Sus gags abren casi todas las películas." },
  { cat:"animacion", dif:2, q:"En la saga 'Madagascar', ¿qué grupo de animales planea fugas con precisión militar?",
    ops:["Los pingüinos","Los lémures","Los leones","Los hipopótamos"], ok:0,
    pista:"'Sonrían y saluden.'", dato:"Tuvieron su propia película spin-off." },
  { cat:"animacion", dif:2, q:"¿Qué actor pone la voz original al 'Gato con Botas' en la saga de Shrek?",
    ops:["Antonio Banderas","Eddie Murphy","Mike Myers","Javier Bardem"], ok:0,
    pista:"Pone ojitos tiernos para convencer.", dato:"El personaje tuvo dos películas propias." },
  { cat:"animacion", dif:3, q:"¿Qué película japonesa de Makoto Shinkai (2016) trata sobre dos jóvenes que intercambian cuerpos?",
    ops:["Your Name (Kimi no Na wa)","El viaje de Chihiro","Una voz silenciosa","Weathering With You"], ok:0,
    pista:"Un cometa une sus destinos.", dato:"Fue un fenómeno de taquilla mundial." },
  { cat:"animacion", dif:3, q:"¿Qué película de Ghibli (2004) sigue a una joven hechizada y un mago en un castillo con patas?",
    ops:["El castillo ambulante","Ponyo","El viaje de Chihiro","Nausicaä"], ok:0,
    pista:"Está basada en una novela de Diana Wynne Jones.", dato:"La dirigió Hayao Miyazaki." },
  { cat:"animacion", dif:3, q:"¿Qué película animada española de 2019 cuenta un origen de Santa Claus y un cartero?",
    ops:["Klaus","Tadeo Jones","Planet 51","Las aventuras de Tadeo"], ok:0,
    pista:"Mezcla animación 2D con luz muy elaborada.", dato:"Fue nominada al Oscar a Mejor Película Animada." },
  { cat:"animacion", dif:2, q:"¿Cuál es la canción pegadiza de 'La Gran Aventura Lego'?",
    ops:["'Todo es genial' (Everything is Awesome)","'Libre soy'","'No se habla de Bruno'","'Bajo el mar'"], ok:0,
    pista:"Todo el mundo de la peli es de bloques.", dato:"La frase se volvió un meme instantáneo." },
  { cat:"animacion", dif:3, q:"¿Qué estudio británico de animación con plastilina creó a 'Wallace y Gromit'?",
    ops:["Aardman","Laika","Ghibli","Illumination"], ok:0,
    pista:"También hizo 'Pollitos en fuga'.", dato:"Trabajan con la técnica del stop-motion en plastilina." },

  /* --- Cine Argentino y Latino --- */
  { cat:"argentino", dif:2, q:"¿Qué película de Campanella (2001) tiene a Darín cumpliendo el sueño de boda de su madre con Alzheimer?",
    ops:["El hijo de la novia","Luna de Avellaneda","El secreto de sus ojos","El mismo amor, la misma lluvia"], ok:0,
    pista:"Norma Aleandro y Héctor Alterio hacen de los padres.", dato:"Estuvo nominada al Oscar a Mejor Película Extranjera." },
  { cat:"argentino", dif:3, q:"¿Cuál fue la última película de Fabián Bielinsky (2005), con Darín como un taxidermista?",
    ops:["El aura","Nueve reinas","El robo del siglo","Plata quemada"], ok:0,
    pista:"El protagonista planea un robo perfecto en su mente.", dato:"Bielinsky falleció al año siguiente, con solo dos películas." },
  { cat:"argentino", dif:3, q:"¿Qué película chilena de 2004 mira el golpe de 1973 a través de dos niños amigos?",
    ops:["Machuca","No","Una mujer fantástica","Gloria"], ok:0,
    pista:"La dirigió Andrés Wood.", dato:"Su amistad cruza las clases sociales de Santiago." },
  { cat:"argentino", dif:3, q:"¿Qué película chilena de Pablo Larraín (2012) recrea la campaña del plebiscito contra Pinochet?",
    ops:["No","El Conde","Neruda","Tony Manero"], ok:0,
    pista:"Gael García Bernal hace de publicista.", dato:"Estuvo nominada al Oscar a Mejor Película Extranjera." },
  { cat:"argentino", dif:3, q:"¿Qué película argentina de María Luisa Bemberg (1984) narra el romance prohibido de Camila O'Gorman?",
    ops:["Camila","Yo, la peor de todas","Miss Mary","Señora de nadie"], ok:0,
    pista:"Una joven se enamora de un cura en la época de Rosas.", dato:"Estuvo nominada al Oscar a Mejor Película Extranjera." },
  { cat:"argentino", dif:3, q:"¿Qué película peruana de Claudia Llosa ganó el Oso de Oro de Berlín en 2009?",
    ops:["La teta asustada","Madeinusa","Magallanes","Wiñaypacha"], ok:0,
    pista:"Habla de un trauma heredado de la época del terrorismo.", dato:"También fue nominada al Oscar extranjero." },
  { cat:"argentino", dif:3, q:"¿Qué película colombiana de Ciro Guerra (2015), en blanco y negro, fue la primera de su país nominada al Oscar?",
    ops:["El abrazo de la serpiente","Monos","Pájaros de verano","La estrategia del caracol"], ok:0,
    pista:"Un chamán guía a exploradores por el Amazonas.", dato:"Mezcla varias lenguas indígenas." },
  { cat:"argentino", dif:3, q:"¿Qué película argentina de 1998 sobre tres jóvenes marginales marcó el 'Nuevo Cine Argentino'?",
    ops:["Pizza, birra, faso","Mundo grúa","Un oso rojo","El bonaerense"], ok:0,
    pista:"Su título nombra tres 'placeres' callejeros.", dato:"La dirigieron Caetano y Stagnaro." },
  { cat:"argentino", dif:2, q:"¿Qué película de 2015 tiene a Ricardo Darín cuidando a un amigo enfermo, junto a Javier Cámara?",
    ops:["Truman","Un cuento chino","Tiempo de valientes","Kóblic"], ok:0,
    pista:"Un viaje para despedirse, con un perro de por medio.", dato:"Darín ganó el premio Goya por este papel." },
  { cat:"argentino", dif:3, q:"¿Qué película de Marcelo Piñeyro (2002), con Darín, muestra una familia escondiéndose durante la dictadura?",
    ops:["Kamchatka","Plata quemada","Cenizas del paraíso","Las viudas de los jueves"], ok:0,
    pista:"El título es el nombre de un lugar en el juego TEG.", dato:"Fue la candidata argentina al Oscar ese año." },
  { cat:"argentino", dif:3, q:"¿Qué película de Marcelo Piñeyro (2000), basada en una novela de Ricardo Piglia, sigue a unos ladrones amantes?",
    ops:["Plata quemada","Caballos salvajes","El método","Kamchatka"], ok:0,
    pista:"Leonardo Sbaraglia y Eduardo Noriega la protagonizan.", dato:"Está inspirada en un robo y fuga reales de 1965." },
  { cat:"argentino", dif:2, q:"¿Qué película de Pablo Trapero (2010) tiene a Darín como un abogado que ronda accidentes?",
    ops:["Carancho","Leonera","El Clan","Elefante blanco"], ok:0,
    pista:"'Carancho' es el que lucra con las desgracias ajenas.", dato:"Martina Gusman lo acompaña como médica de guardia." },

  /* --- Mix de Cine --- */
  { cat:"mixto", dif:3, q:"¿Cuál es la última palabra que pronuncia el protagonista de 'Ciudadano Kane' (1941)?",
    ops:["'Rosebud'","'Adiós'","'Dinero'","'Madre'"], ok:0,
    pista:"Es el misterio que estructura toda la película.", dato:"Orson Welles la dirigió con apenas 25 años." },
  { cat:"mixto", dif:2, q:"¿Qué pareja protagoniza el clásico 'Casablanca' (1942)?",
    ops:["Humphrey Bogart e Ingrid Bergman","Clark Gable y Vivien Leigh","Cary Grant y Grace Kelly","Fred Astaire y Ginger Rogers"], ok:0,
    pista:"'Siempre nos quedará París.'", dato:"'Tócala otra vez, Sam' es una frase que en realidad nunca se dice tal cual." },
  { cat:"mixto", dif:2, q:"¿Qué película de Spielberg (1993), en blanco y negro, retrata el Holocausto?",
    ops:["La lista de Schindler","El pianista","La vida es bella","El niño con el pijama de rayas"], ok:0,
    pista:"Una nena con tapado rojo es el único color.", dato:"Ganó 7 Oscars, incluido Mejor Película." },
  { cat:"mixto", dif:3, q:"En 'El club de la pelea' (Fight Club), ¿cuál es la primera regla?",
    ops:["No hablar del club de la pelea","No pelear de a dos","No usar zapatos","No traer amigos"], ok:0,
    pista:"La dirigió David Fincher.", dato:"Brad Pitt y Edward Norton la protagonizan; tiene un giro famoso." },
  { cat:"mixto", dif:3, q:"¿Qué película de David Fincher (1995) gira en torno a asesinatos basados en los 7 pecados capitales?",
    ops:["Seven (Pecados capitales)","Zodiaco","El silencio de los inocentes","Reservoir Dogs"], ok:0,
    pista:"'¿Qué hay en la caja?'", dato:"Brad Pitt y Morgan Freeman investigan los crímenes." },
  { cat:"mixto", dif:2, q:"¿Qué película de 2008 sobre un joven indio en un concurso de preguntas ganó el Oscar a Mejor Película?",
    ops:["Quisiera ser millonario (Slumdog Millionaire)","Gandhi","La vida de Pi","El hotel Marigold"], ok:0,
    pista:"La dirigió Danny Boyle.", dato:"Cada pregunta del concurso conecta con su vida." },
  { cat:"mixto", dif:3, q:"¿Qué película de Iñárritu (2014), que parece un solo plano continuo, ganó Mejor Película?",
    ops:["Birdman","Whiplash","Boyhood","El Renacido"], ok:0,
    pista:"Michael Keaton hace de un actor que fue superhéroe.", dato:"Casi toda transcurre en un teatro de Broadway." },
  { cat:"mixto", dif:2, q:"¿Qué película ganó Mejor Película en 2017 tras un famoso error con el sobre en la ceremonia?",
    ops:["Moonlight","La La Land","Manchester junto al mar","Comanchería"], ok:0,
    pista:"Primero anunciaron a la otra por error.", dato:"Fue la primera película con elenco mayormente afroamericano y temática LGBT en ganar." },
  { cat:"mixto", dif:2, q:"¿Qué película de 2021 de Chloé Zhao, con Frances McDormand viviendo en una van, ganó Mejor Película?",
    ops:["Nomadland","Minari","El padre","Mank"], ok:0,
    pista:"Sigue a nómades modernos por el oeste de EE.UU.", dato:"Zhao fue la primera mujer no blanca en ganar Mejor Dirección." },
  { cat:"mixto", dif:3, q:"¿Qué actor ganó el Oscar por interpretar al sádico Anton Chigurh en 'Sin lugar para los débiles'?",
    ops:["Javier Bardem","Benicio del Toro","Gael García Bernal","Antonio Banderas"], ok:0,
    pista:"Usa una pistola de aire comprimido para ganado.", dato:"La dirigieron los hermanos Coen y ganó Mejor Película (2008)." },
  { cat:"mixto", dif:3, q:"¿Qué actor ganó el Oscar por su profesor de jazz despiadado en 'Whiplash' (2014)?",
    ops:["J.K. Simmons","Miles Teller","Edward Norton","Mark Ruffalo"], ok:0,
    pista:"'¿Apuraste o atrasaste?'", dato:"La dirigió Damien Chazelle, que luego hizo 'La La Land'." },
  { cat:"mixto", dif:2, q:"¿Qué actor interpretó a Freddie Mercury en 'Bohemian Rhapsody' (2018) y ganó el Oscar?",
    ops:["Rami Malek","Taron Egerton","Sacha Baron Cohen","Eddie Redmayne"], ok:0,
    pista:"Recrea el show de Queen en Live Aid.", dato:"Taron Egerton, en cambio, hizo de Elton John en 'Rocketman'." },
  { cat:"mixto", dif:2, q:"¿En qué película de 2018 Lady Gaga y Bradley Cooper cantan 'Shallow'?",
    ops:["Nace una estrella (A Star is Born)","La La Land","El gran showman","Rocketman"], ok:0,
    pista:"Él es un músico en decadencia; ella, una estrella en ascenso.", dato:"'Shallow' ganó el Oscar a Mejor Canción." },
  { cat:"mixto", dif:3, q:"¿Qué actriz ganó el Oscar por la película de ballet 'El cisne negro' (2010)?",
    ops:["Natalie Portman","Mila Kunis","Anne Hathaway","Jennifer Lawrence"], ok:0,
    pista:"Su personaje se obsesiona con la perfección.", dato:"La dirigió Darren Aronofsky." }
];
